spring:
  datasource:
    url: jdbc:postgresql://yamanote.proxy.rlwy.net:37941/railway
    username: postgres
    password: DqQYlpmndFQdWfHpFsADEOTCQBklsTKj
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true