spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/joined_table_inheritance
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  file:
    name: logging/log-file.log
  level:
    root: info