spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: HtFJSlTjMOZTHGLDJpXHFuVYlXeRfZGw
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true