spring:
  application:
    name: joined-table-inheritance
  profiles:
    active: railway
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
jwt:
  access:
    token:
      key: A6465486W46546FEHUKnjhguyjhba15364563
      expiration: 50000000